-- ============================================================================
-- Migration: 2026052701_add_embedding_hnsw_index
-- Purpose:   Create the HNSW index on movie_embeddings.embedding to
--            accelerate similarity-based queries.
--
-- Why this migration is separate from 2026052700:
--   The HNSW index is most efficient when built over a populated table.
--   Building it over an empty table would produce a degenerate index
--   that would have to be rebuilt anyway. By the time this migration
--   runs, the embeddings have already been generated by
--   python/scripts/13_generate_embeddings.py.
--
-- Why HNSW and not IVFFlat:
--   - HNSW achieves higher recall (returns the true nearest neighbors
--     more reliably) at the cost of higher build time.
--   - IVFFlat requires choosing a 'lists' parameter that depends on
--     the row count; HNSW has no such dependency, which keeps the
--     schema simpler over time.
--   - 44k vectors is small enough that HNSW build time (~30-60s) is
--     acceptable.
--
-- Why cosine distance:
--   Cosine distance is the standard similarity metric for text
--   embeddings produced by sentence-transformers models. It is
--   invariant to vector magnitude, which prevents bias by text length.
--   The operator class 'vector_cosine_ops' tells PostgreSQL to use
--   cosine distance (operator <=>) when querying via this index.
--
-- Parameters:
--   - m = 16             : default. Connections per node in the graph.
--   - ef_construction = 64 : default. Candidates evaluated during build.
--   These defaults are recommended by the pgvector docs for datasets
--   of our order of magnitude.
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_movie_embeddings_hnsw_cosine
    ON movie_embeddings
        USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

COMMENT ON INDEX idx_movie_embeddings_hnsw_cosine IS
    'HNSW index for cosine-distance similarity search on movie embeddings.
     Used by the /movies/{id}/similar endpoint to retrieve nearest neighbors
     in logarithmic time instead of full table scan.';