-- ============================================================================
-- Migration: 2026052702_resize_embeddings_to_768
-- Purpose:   Resize the embedding column from vector(384) to vector(768) to
--            host vectors produced by all-mpnet-base-v2 instead of
--            all-MiniLM-L6-v2.
--
-- Why this is a destructive migration:
--   PostgreSQL/pgvector does not support changing the dimension of an
--   existing vector column in place. The column must be dropped and
--   recreated. As a consequence, all existing embeddings (produced by
--   the previous 384-dim model) are discarded; the loader will
--   regenerate them with the new model.
--
-- Why drop the HNSW index too:
--   The HNSW index is bound to the column. When the column is dropped,
--   the index is dropped automatically. We do not need to drop it
--   explicitly here, but we do need to recreate it after the new
--   embeddings have been generated (migration 2026052703).
--
-- Procedure:
--   1. Drop the existing embedding column (cascades to dependent
--      indexes).
--   2. Add a new embedding column with dimension 768, initially NULL
--      (because there are no embeddings yet for the new model).
--   3. Truncate model_name and source_text_hash to leave the table in
--      a consistent state: every row will be regenerated by the loader,
--      so existing metadata is stale.
--
-- The script python/scripts/13_generate_embeddings.py is run AFTER
-- this migration to repopulate the table, and the HNSW index is
-- recreated in the next migration.
-- ============================================================================

-- Step 1: drop the dependent column (this also drops indexes that
-- include it, namely idx_movie_embeddings_hnsw_cosine).
ALTER TABLE movie_embeddings DROP COLUMN embedding;

-- Step 2: add the new 768-dim column.
ALTER TABLE movie_embeddings ADD COLUMN embedding vector(768);

-- Step 3: clear the rows. All existing rows correspond to the old
-- model and would have a NULL embedding right now; cleaner to start
-- empty so the loader can do its idempotency check correctly.
TRUNCATE TABLE movie_embeddings;

-- Step 4: make the new column NOT NULL once again (the constraint
-- was lost when the column was dropped and recreated).
ALTER TABLE movie_embeddings ALTER COLUMN embedding SET NOT NULL;

COMMENT ON COLUMN movie_embeddings.embedding IS
    '768-dimensional dense vector produced by all-mpnet-base-v2.
     Cosine distance is the default similarity metric (operator <=>).';